![jupyter](img/itq-logo.png )

## Machine Learning - Normalización

![jupyter](img/python-logo.png )

*Lesly Noemi Becerra Campaña*

En la terminal, ejecutar: pip install scikit-learn

In [18]:
from sklearn import preprocessing
import numpy as np

In [19]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [20]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [21]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [22]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


## Ejercicio en casa

In [23]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  4., -1.]])

# Normalizar los datos de "X_test"
# ???
print(X_test)

[[ 1. -3.  2.]
 [ 3.  0.  0.]
 [ 0.  4. -1.]]


In [24]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
normalizer.fit(X_train)
X_test_norm = normalizer.transform(X_test)

print(X_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


## Ejercicio Propio

In [25]:
X_lesly = np.array([[ -1., 2., -3.],
                    [ 4., -5., 6. ],
                    [ -7., -8., 0.]])

print(X_lesly)

[[-1.  2. -3.]
 [ 4. -5.  6.]
 [-7. -8.  0.]]


In [26]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_lesly_norm = normalizer.fit_transform(X_lesly)

In [27]:
print(X_lesly_norm)

[[0.54545455 1.         0.        ]
 [1.         0.3        1.        ]
 [0.         0.         0.33333333]]


In [28]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_lesly_2 = np.copy(X_lesly)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_lesly)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_lesly_norm_2 = f.transform(X_lesly)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_lesly_norm, X_lesly_norm_2))

True
